### ISSUE TITLE
Can not work under emacs 24.3

### ISSUE THREAD

**Issue by biaji** [dcolascione/logcat-mode#1]
Compile Warning:
Warning: Unknown defun property `interactive-only' in logcat-filter-pid
Warning: Unknown defun property`interactive-only' in logcat-filter-tid
Warning: Unknown defun property `interactive-only' in logcat-filter-priority
Warning: Unknown defun property`interactive-only' in logcat-filter-tag
Warning: Unknown defun property `interactive-only' in logcat-filter-message

Runtime Error:
let: Symbol's function definition is void: add-function

**Comment by dcolascione** [comment]
Sorry --- Emacs 24.x isn't supported.
